---
trigger: 
- main

parameters:
- name: goals
  displayName: Building steps  
  type: string
  default: 'package'
- name: jdkVersion
  type: string
  default: '17'

pool:
  name: Default

stages:
- stage: Built
  displayName: Build using maven 
  jobs:
  - job: Build
    displayName: Maven Build
    steps:
    - task: SonarCloudPrepare@2
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'demondevops1'
        scannerMode: 'Other'
        extraProperties: |
          sonar.exclusions= **/*.bin
          sonar.projectKey= demondevops1_SPC-BUILD-TEST
          sonar.projectName= SPC-BUILD-TEST
    - task: Maven@4
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: ${{ parameters.goals }}
        publishJUnitResults: true 
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: ${{ parameters.jdkVersion }}
        mavenVersionOption: 'Default'

    - task: SonarCloudAnalyze@2
      inputs:
        jdkversion: 'JAVA_HOME'
    
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/target/spring-petclinic-3.3.0-SNAPSHOT.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Drop'

  





